/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toye.nakamurazacharyu2a5summative;
import java.text.DecimalFormat;
/**
 *
 * @author Zachary Toye-Nakamura
 * Aug 4, 2023
 * A short program using a GUI to give the user a multiple choice quiz with stats and feedback
 * Quiz statistics displays # of correct answer / # of answers (eg. if you only answer 3 questions and 2 correctly it's 66.7%)
 */
public class frmMultipleChoiceQuiz extends javax.swing.JFrame {
    // Declaring all variables that are needed.
    
    // Declaring the decimal format which rounds to 1 decimal.
    DecimalFormat df1 = new DecimalFormat("0.0");
    
    // Declaring the correct answer for question 1, lowercase
    final String STRQ1CORRECTANSLOWER = "d";
    // Declaring the correct answer for question 1, uppercase
    final String STRQ1CORRECTANSUPPER = "D";
    // Declaring the correct answer for question 2, lowercase
    final String STRQ2CORRECTANSLOWER = "b";
    // Declaring the correct answer for question 2, uppercase
    final String STRQ2CORRECTANSUPPER = "B";
    // Declaring the correct answer for question 3, lowercase
    final String STRQ3CORRECTANSLOWER = "a";
    // Declaring the correct answer for question 3, uppercase
    final String STRQ3CORRECTANSUPPER = "A";
    // Declaring the correct answer for question 4, lowercase
    final String STRQ4CORRECTANSLOWER = "c";
    // Declaring the correct answer for question 4, uppercase
    final String STRQ4CORRECTANSUPPER = "C";
    // Declaring the correct answer for question 5, lowercase
    final String STRQ5CORRECTANSLOWER = "d";
    // Declaring the correct answer for question 5, uppercase
    final String STRQ5CORRECTANSUPPER = "D";
    
    // Declaring the status of question 1, -1 for unanswered, 0 for incorrect, 1 for correct
    int intQ1Status = -1;
    // Declaring the status of question 2, -1 for unanswered, 0 for incorrect, 1 for correct
    int intQ2Status = -1;
    // Declaring the status of question 3, -1 for unanswered, 0 for incorrect, 1 for correct
    int intQ3Status = -1;
    // Declaring the status of question 4, -1 for unanswered, 0 for incorrect, 1 for correct
    int intQ4Status = -1;
    // Declaring the status of question 5, -1 for unanswered, 0 for incorrect, 1 for correct
    int intQ5Status = -1;
    // Declaring the number of correct questions
    int intCorrect = 0;
    // Declaring the number of incorrect questions 
    int intIncorrect = 0;
    
    
    /**
     * Creates new form frmMultipleChoiceQuiz
     */
    public frmMultipleChoiceQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainTitle = new javax.swing.JLabel();
        lblQ1text = new javax.swing.JLabel();
        lblQ1Answers = new javax.swing.JLabel();
        lblQ2text = new javax.swing.JLabel();
        lblQ2Answers = new javax.swing.JLabel();
        lblQ3text = new javax.swing.JLabel();
        lblQ3Answers = new javax.swing.JLabel();
        lblQ4text = new javax.swing.JLabel();
        lblQ4Answers = new javax.swing.JLabel();
        lblQ5text = new javax.swing.JLabel();
        lblQ5Answers = new javax.swing.JLabel();
        btnQ1Check = new javax.swing.JButton();
        btnQ2Check = new javax.swing.JButton();
        btnQ3Check = new javax.swing.JButton();
        btnQ4Check = new javax.swing.JButton();
        btnQ5Check = new javax.swing.JButton();
        lblQ1Feedback = new javax.swing.JLabel();
        lblQ2Feedback = new javax.swing.JLabel();
        lblQ3Feedback = new javax.swing.JLabel();
        lblQ4Feedback = new javax.swing.JLabel();
        lblQ5Feedback = new javax.swing.JLabel();
        txtQ1Response = new javax.swing.JTextField();
        txtQ2Response = new javax.swing.JTextField();
        txtQ3Response = new javax.swing.JTextField();
        txtQ4Response = new javax.swing.JTextField();
        txtQ5Response = new javax.swing.JTextField();
        lblStatsTitle = new javax.swing.JLabel();
        lblAnsweredCorrect = new javax.swing.JLabel();
        lblAnsweredIncorrect = new javax.swing.JLabel();
        lblPercentageCorrect = new javax.swing.JLabel();
        lblNumCorrect = new javax.swing.JLabel();
        lblPercentCorrect = new javax.swing.JLabel();
        lblNumIncorrect = new javax.swing.JLabel();
        btnCalcStats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMainTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMainTitle.setText("A Very Random Multiple Choice Quiz");

        lblQ1text.setText("1. Which of the following is the atomic symbol for Gold? ");

        lblQ1Answers.setText("a) Go     b) Ag     c) Gl     d) Au");

        lblQ2text.setText("2. What is the VESPR shape of CH4 (Carbon Tetrahydride)?");

        lblQ2Answers.setText("a) Bent b) Tetrahedral c) T-shaped d) Linear");

        lblQ3text.setText("3. What is the default recusion limit in Python3?");

        lblQ3Answers.setText("a) 999   b) 1000   c) 9999   d) 4999");

        lblQ4text.setText("4. How many neutrons are there in Oxygen?");

        lblQ4Answers.setText("a) 16        b) 4        c) 8         d) 9");

        lblQ5text.setText("5. Which of the following numbers is prime?");

        lblQ5Answers.setText("a) 1e9+9 b) 1677 c) 1e234+2 d) 1e9+7");

        btnQ1Check.setText("Check");
        btnQ1Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ1CheckActionPerformed(evt);
            }
        });

        btnQ2Check.setText("Check");
        btnQ2Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ2CheckActionPerformed(evt);
            }
        });

        btnQ3Check.setText("Check");
        btnQ3Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ3CheckActionPerformed(evt);
            }
        });

        btnQ4Check.setText("Check");
        btnQ4Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ4CheckActionPerformed(evt);
            }
        });

        btnQ5Check.setText("Check");
        btnQ5Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ5CheckActionPerformed(evt);
            }
        });

        lblQ1Feedback.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblQ2Feedback.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblQ3Feedback.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblQ4Feedback.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblQ5Feedback.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtQ1Response.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtQ1Response.setToolTipText("");
        txtQ1Response.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ1ResponseActionPerformed(evt);
            }
        });

        txtQ2Response.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtQ2Response.setToolTipText("");
        txtQ2Response.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ2ResponseActionPerformed(evt);
            }
        });

        txtQ3Response.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtQ3Response.setToolTipText("");
        txtQ3Response.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ3ResponseActionPerformed(evt);
            }
        });

        txtQ4Response.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtQ4Response.setToolTipText("");
        txtQ4Response.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ4ResponseActionPerformed(evt);
            }
        });

        txtQ5Response.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtQ5Response.setToolTipText("");
        txtQ5Response.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ5ResponseActionPerformed(evt);
            }
        });

        lblStatsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatsTitle.setText("Quiz statistics ");

        lblAnsweredCorrect.setText("Number of question answered correctly:");

        lblAnsweredIncorrect.setText("Number of question answered incorrectly:");

        lblPercentageCorrect.setText("Percent of question answered correctly:");

        lblNumCorrect.setText("0");

        lblPercentCorrect.setText("0.0%");

        lblNumIncorrect.setText("0");

        btnCalcStats.setText("Get Statistics");
        btnCalcStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ3text, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQ4text, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQ5text, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQ2text, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQ1text, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE))
                        .addGap(6, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStatsTitle)
                                .addGap(40, 40, 40)
                                .addComponent(btnCalcStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPercentageCorrect)
                                    .addGap(42, 42, 42)
                                    .addComponent(lblPercentCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblAnsweredIncorrect)
                                    .addGap(28, 28, 28)
                                    .addComponent(lblNumIncorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblAnsweredCorrect)
                                    .addGap(38, 38, 38)
                                    .addComponent(lblNumCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblQ4Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQ5Answers, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQ4Answers, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQ3Answers, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQ2Answers, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQ1Answers, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQ1Response, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQ2Response, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQ3Response, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQ4Response, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQ5Response, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnQ2Check)
                                    .addComponent(btnQ1Check)
                                    .addComponent(btnQ3Check)
                                    .addComponent(btnQ4Check)
                                    .addComponent(btnQ5Check)))
                            .addComponent(lblQ3Feedback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQ1Feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQ2Feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQ5Feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMainTitle)
                .addGap(35, 35, 35)
                .addComponent(lblQ1text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQ1Response, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQ1Check)
                    .addComponent(lblQ1Answers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQ1Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQ2text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQ2Check)
                    .addComponent(lblQ2Answers)
                    .addComponent(txtQ2Response, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQ2Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQ3text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQ3Check)
                    .addComponent(lblQ3Answers)
                    .addComponent(txtQ3Response, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQ3Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblQ4text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ4Answers)
                    .addComponent(btnQ4Check)
                    .addComponent(txtQ4Response, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQ4Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblQ5text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ5Answers)
                    .addComponent(btnQ5Check)
                    .addComponent(txtQ5Response, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQ5Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatsTitle)
                    .addComponent(btnCalcStats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsweredCorrect)
                    .addComponent(lblNumCorrect))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsweredIncorrect)
                    .addComponent(lblNumIncorrect))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPercentageCorrect)
                    .addComponent(lblPercentCorrect))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQ1ResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ1ResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ1ResponseActionPerformed

    private void btnQ1CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ1CheckActionPerformed
        // User checks their question 1
        // Get the users answer from input
        String strUserAns = txtQ1Response.getText();
        
        // If the user's input is the correct answer (uppercase or lowercase)
        if (strUserAns.equals(STRQ1CORRECTANSLOWER) || strUserAns.equals(STRQ1CORRECTANSUPPER)) 
        {
            // Give the feedback that it's correct
            lblQ1Feedback.setText("That is correct!");
            // If the question was previously incorrect, decrement the number of incorrect questions
            if (intQ1Status == 0) intIncorrect-=1;
            // Increment the number of correct questions if not already correct
            if (intQ1Status != 1) intCorrect+=1;
            // Set the status of the question to correctly answered
            intQ1Status = 1;
        }
        else 
        {
            // Give the feed back that it's wrong
            lblQ1Feedback.setText("INCORRECT, the correct answer is (d) Au");
            // If the question was previously correct, decrement the number of correct questions
            if (intQ1Status == 1) intCorrect-=1;
            // Increment the number of incorrect questions, if not already incorrect
            if (intQ1Status != 0) intIncorrect+=1;
            // Set the status of the question to incorrectly answered
            intQ1Status = 0;
        }
    }//GEN-LAST:event_btnQ1CheckActionPerformed

    private void btnQ2CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ2CheckActionPerformed
        // User checks their question 2
        // Get the users answer from input
        String strUserAns = txtQ2Response.getText();
        
        if (strUserAns.equals(STRQ2CORRECTANSLOWER) || strUserAns.equals(STRQ2CORRECTANSUPPER)) 
        {
            // Give the feedback that it's correct
            // If the user's input is the correct answer (uppercase or lowercase)
            lblQ2Feedback.setText("That is correct!");
            // If the question was previously incorrect, decrement the number of incorrect questions
            if (intQ2Status == 0) intIncorrect-=1;
            // Increment the number of correct questions if not already correct
            if (intQ2Status != 1) intCorrect+=1;
            // Set the status of the question to correctly answered
            intQ2Status = 1;
        }
        else 
        {
            // Give the feed back that it's wrong
            lblQ2Feedback.setText("INCORRECT, the correct answer is (b) Tetrahedral");
            // If the question was previously correct, decrement the number of correct questions
            if (intQ2Status == 1) intCorrect-=1;
            // Increment the number of incorrect questions, if not already incorrect
            if (intQ2Status != 0) intIncorrect+=1;
            // Set the status of the question to incorrectly answered
            intQ2Status = 0;
        }
    }//GEN-LAST:event_btnQ2CheckActionPerformed

    private void btnQ3CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ3CheckActionPerformed
        // User checks their question 3
        // Get the users answer from input
        String strUserAns = txtQ3Response.getText();
        
        // If the user's input is the correct answer (uppercase or lowercase)
        if (strUserAns.equals(STRQ3CORRECTANSLOWER) || strUserAns.equals(STRQ3CORRECTANSUPPER)) 
        {
            // Give the feedback that it's correct
            lblQ3Feedback.setText("That is correct!");
            // If the question was previously incorrect, decrement the number of incorrect questions
            if (intQ3Status == 0) intIncorrect-=1;
            // Increment the number of correct questions if not already correct
            if (intQ3Status != 1) intCorrect+=1;
            // Set the status of the question to correctly answered
            intQ3Status = 1;
        }
        else 
        {
            // Give the feed back that it's wrong
            lblQ3Feedback.setText("INCORRECT, the correct answer is (a) 999");
            // If the question was previously correct, decrement the number of correct questions
            if (intQ3Status == 1) intCorrect-=1;
            // Increment the number of incorrect questions, if not already incorrect
            if (intQ3Status != 0) intIncorrect+=1;
            // Set the status of the question to incorrectly answered
            intQ3Status = 0;
        }
    }//GEN-LAST:event_btnQ3CheckActionPerformed

    private void btnQ4CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ4CheckActionPerformed
        // User checks their question 1
        // Get the users answer from input
        String strUserAns = txtQ4Response.getText();
        
        // If the user's input is the correct answer (uppercase or lowercase)
        if (strUserAns.equals(STRQ4CORRECTANSLOWER) || strUserAns.equals(STRQ4CORRECTANSUPPER)) 
        {
            // Give the feedback that it's correct
            lblQ4Feedback.setText("That is correct!");
            // If the question was previously incorrect, decrement the number of incorrect questions
            if (intQ4Status == 0) intIncorrect-=1;
            // Increment the number of correct questions if not already correct
            if (intQ4Status != 1) intCorrect+=1;
            // Set the status of the question to correctly answered
            intQ4Status = 1;
        }
        else 
        {
            // Give the feed back that it's wrong
            lblQ4Feedback.setText("INCORRECT, the correct answer is (c) 8");
            // If the question was previously correct, decrement the number of correct questions
            if (intQ4Status == 1) intCorrect-=1;
            // Increment the number of incorrect questions, if not already incorrect
            if (intQ4Status != 0) intIncorrect+=1;
            // Set the status of the question to incorrectly answered
            intQ4Status = 0;
        }
    }//GEN-LAST:event_btnQ4CheckActionPerformed

    private void btnQ5CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ5CheckActionPerformed
        // User checks their question 1
        // Get the users answer from input
        String strUserAns = txtQ5Response.getText();
        
        // If the user's input is the correct answer (uppercase or lowercase)
        if (strUserAns.equals(STRQ5CORRECTANSLOWER) || strUserAns.equals(STRQ5CORRECTANSUPPER)) 
        {
            // Give the feedback that it's correct
            lblQ5Feedback.setText("That is correct!");
            // If the question was previously incorrect, decrement the number of incorrect questions
            if (intQ5Status == 0) intIncorrect-=1;
            // Increment the number of correct questions if not already correct
            if (intQ5Status != 1) intCorrect+=1;
            // Set the status of the question to correctly answered
            intQ5Status = 1;
        }
        else 
        {
            // Give the feed back that it's wrong
            lblQ5Feedback.setText("INCORRECT, the correct answer is (d) 1e9+7");
            // If the question was previously correct, decrement the number of correct questions
            if (intQ5Status == 1) intCorrect-=1;
            // Increment the number of incorrect questions, if not already incorrect
            if (intQ5Status != 0) intIncorrect+=1;
            // Set the status of the question to incorrectly answered
            intQ5Status = 0;
        }
    }//GEN-LAST:event_btnQ5CheckActionPerformed

    private void txtQ2ResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ2ResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ2ResponseActionPerformed

    private void txtQ3ResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ3ResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ3ResponseActionPerformed

    private void txtQ4ResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ4ResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ4ResponseActionPerformed

    private void txtQ5ResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ5ResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ5ResponseActionPerformed

    private void btnCalcStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcStatsActionPerformed
        // The user wants to see statistics about their quiz
        // Set the text of the number of correct questions
        lblNumCorrect.setText(""+intCorrect);
        // Set the text of the number of incorrect questions
        lblNumIncorrect.setText(""+intIncorrect);
        // Set the text of the percentage of correctly answered questions (number of correct/ number of questions answer)
        lblPercentCorrect.setText(df1.format((double)intCorrect/(double)(intCorrect+intIncorrect)*100)+"%");
    }//GEN-LAST:event_btnCalcStatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMultipleChoiceQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcStats;
    private javax.swing.JButton btnQ1Check;
    private javax.swing.JButton btnQ2Check;
    private javax.swing.JButton btnQ3Check;
    private javax.swing.JButton btnQ4Check;
    private javax.swing.JButton btnQ5Check;
    private javax.swing.JLabel lblAnsweredCorrect;
    private javax.swing.JLabel lblAnsweredIncorrect;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblNumCorrect;
    private javax.swing.JLabel lblNumIncorrect;
    private javax.swing.JLabel lblPercentCorrect;
    private javax.swing.JLabel lblPercentageCorrect;
    private javax.swing.JLabel lblQ1Answers;
    private javax.swing.JLabel lblQ1Feedback;
    private javax.swing.JLabel lblQ1text;
    private javax.swing.JLabel lblQ2Answers;
    private javax.swing.JLabel lblQ2Feedback;
    private javax.swing.JLabel lblQ2text;
    private javax.swing.JLabel lblQ3Answers;
    private javax.swing.JLabel lblQ3Feedback;
    private javax.swing.JLabel lblQ3text;
    private javax.swing.JLabel lblQ4Answers;
    private javax.swing.JLabel lblQ4Feedback;
    private javax.swing.JLabel lblQ4text;
    private javax.swing.JLabel lblQ5Answers;
    private javax.swing.JLabel lblQ5Feedback;
    private javax.swing.JLabel lblQ5text;
    private javax.swing.JLabel lblStatsTitle;
    private javax.swing.JTextField txtQ1Response;
    private javax.swing.JTextField txtQ2Response;
    private javax.swing.JTextField txtQ3Response;
    private javax.swing.JTextField txtQ4Response;
    private javax.swing.JTextField txtQ5Response;
    // End of variables declaration//GEN-END:variables
}
