/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toye.nakamurazacharyfinalproject;

/**
 *
 * @author zacha
 */
public class frmBlackjackInfo extends javax.swing.JFrame {

    /**
     * Creates new form frmBlackjackInfo
     */
    public frmBlackjackInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblBjInfo1 = new javax.swing.JLabel();
        lblBjInfo2 = new javax.swing.JLabel();
        lblBjInfo3 = new javax.swing.JLabel();
        lblBjInfo4 = new javax.swing.JLabel();
        lblBjInfo7 = new javax.swing.JLabel();
        lblBjInfo5 = new javax.swing.JLabel();
        lblBjInfo6 = new javax.swing.JLabel();
        lblBjInfo8 = new javax.swing.JLabel();
        lblBjInfo9 = new javax.swing.JLabel();
        lblBjInfo10 = new javax.swing.JLabel();
        lblBjInfo11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBack.setText("Back");
        lblBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTitle.setText("Blackjack Info");

        lblBjInfo1.setText("Blackjack is a partially skill-based game, meaning you can increase you odds by playing well,");

        lblBjInfo2.setText("but even when playing perfectly you can't guarantee a win, since it's partially luck-based.");

        lblBjInfo3.setText("Some basic advice when playing is to stop hitting when you have a total of 17 or higher, but if the dealer's");

        lblBjInfo4.setText("face up card is low, under 6 you should stop at 13 because the dealer is likely to bust.");

        lblBjInfo7.setText("Dealer bust out rates");

        lblBjInfo5.setText("Face up card:                     2              3               4               5           6           7           8           9       10(Any)       A");

        lblBjInfo6.setText("35.3%       37.6%      40.3%      42.9%    42.1%     26%    23.9%    23.3%    21.4%       11.7%");

        lblBjInfo8.setText("These rates do change because cards taken out of the deck are not replaced.");

        lblBjInfo9.setText("Card counting is another strategy that can help you get a edge, (when not online as the deck is reset every round).");

        lblBjInfo10.setText("When card counting you keep track of how many high and low cards have been dealt, keep a count in your head ");

        lblBjInfo11.setText("add one when you see a 2-6 dealt, and subtract one when you see a 10 or A dealt, when the count is high, bet more.");

        jLabel1.setText("With perfect play the house will always have ~2% edge against you due to winning ties. If they use more decks and shuffle more.");

        jLabel2.setText("Your odds go down. This is why you should never gamble to win money. YOU WILL ALWAYS LOSE.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBjInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBjInfo2)
                            .addComponent(lblBjInfo4)
                            .addComponent(lblBjInfo3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblBjInfo7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblBjInfo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(lblBjInfo5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBjInfo8)
                            .addComponent(lblBjInfo9)
                            .addComponent(lblBjInfo10)
                            .addComponent(lblBjInfo11)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle)
                    .addComponent(lblBack))
                .addGap(18, 18, 18)
                .addComponent(lblBjInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBjInfo2)
                .addGap(18, 18, 18)
                .addComponent(lblBjInfo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBjInfo4)
                .addGap(18, 18, 18)
                .addComponent(lblBjInfo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBjInfo7)
                    .addComponent(lblBjInfo6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBjInfo8)
                .addGap(18, 18, 18)
                .addComponent(lblBjInfo9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBjInfo10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBjInfo11)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBackActionPerformed
        // TODO add your handling code here:
        // Make the blackjack visible
        new frmBlackjack().setVisible(true);
        // Get rid of this frame, making the blackjack frame the current "main" frame.
        this.dispose();
    }//GEN-LAST:event_lblBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBlackjackInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBlackjackInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBlackjackInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBlackjackInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBlackjackInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lblBack;
    private javax.swing.JLabel lblBjInfo1;
    private javax.swing.JLabel lblBjInfo10;
    private javax.swing.JLabel lblBjInfo11;
    private javax.swing.JLabel lblBjInfo2;
    private javax.swing.JLabel lblBjInfo3;
    private javax.swing.JLabel lblBjInfo4;
    private javax.swing.JLabel lblBjInfo5;
    private javax.swing.JLabel lblBjInfo6;
    private javax.swing.JLabel lblBjInfo7;
    private javax.swing.JLabel lblBjInfo8;
    private javax.swing.JLabel lblBjInfo9;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
