/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toye.nakamurazacharyu3a3ast;
import java.lang.Math;
/**
 *
 * @author Zachary Toye-Nakamura
 * Date: Aug 10, 2023
 * 
 * A short program that lets the user place a bet and choose a number. Then 2 dice are rolled. 
 * If the user's number is equal to the dices sum they gain money otherwise they lose money.
 * The last few outcomes are stored and shown.
 * There is also a button that resets the program.
 * 
 * Problems:
 * No error handling or checking if a number is a int.
 */
public class frmU3A3AST extends javax.swing.JFrame {

    /**
     * Creates new form frmU3A3AST
     */
    // Declare the number of faces on the dice
    final int INTNUMFACES = 6;
    // Declare the number of dice rolled, would work better if 2d arrays were allowed
    final int INTNUMDICEROLL = 3;
    // Declare a int to store how many times the bet the user wins, upon winning (and they don't lose the bet money)
    final int INTWINMULTIPLIER = 3; 
    // Declare an array to hold the outcome of the last 5 bets
    String [] strOutcome = new String[5];
    // Declare an array to hold the outcome of the first die during the last 5 bets
    int [] int1stDie = new int[5];
    // Declare an array to hold the outcome of the second die during the last 5 bets
    int [] int2ndDie = new int[5];
    // Declare an array to hold the outcome of the third die during the last 5 bets
    int [] int3rdDie = new int[5];
    // Declare a variable to hold how much money the user has.
    int intMoney = 100;
    
    
    public frmU3A3AST() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtext1 = new javax.swing.JLabel();
        lblSubtext2 = new javax.swing.JLabel();
        lblNumGuessedSubtitle = new javax.swing.JLabel();
        lblBetSubtitle = new javax.swing.JLabel();
        lblMoneySubtitle = new javax.swing.JLabel();
        txtNumberGuessed = new javax.swing.JTextField();
        txtBetAmount = new javax.swing.JTextField();
        lblRemainingMoney = new javax.swing.JLabel();
        lblErrorMessage = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        lblPreviousTitle = new javax.swing.JLabel();
        lblDiceTitle = new javax.swing.JLabel();
        lblOutcomeSubtitle = new javax.swing.JLabel();
        lblTotalTitle = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        lblDiceTotalSubtitle = new javax.swing.JLabel();
        lblDiceResults = new javax.swing.JLabel();
        lblTotalResults = new javax.swing.JLabel();
        lblTotalSubtitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreviousBets = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTitle.setText("Gambling!");

        lblSubtext1.setText("Choose a number and a bet amount. Then 3 6-sided dice will be rolled and summed.");

        lblSubtext2.setText("If you guess the sum of the dice correctly you gain triple your bet, otherwise you lose all the money you bet");

        lblNumGuessedSubtitle.setText("Guess");

        lblBetSubtitle.setText("Bet Amount");

        lblMoneySubtitle.setText("Money");

        txtNumberGuessed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumberGuessed.setText("0");
        txtNumberGuessed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberGuessedActionPerformed(evt);
            }
        });

        txtBetAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBetAmount.setText("0");

        lblRemainingMoney.setText("$100");

        btnConfirm.setText("Place bet");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        lblPreviousTitle.setText("Previous results");

        lblDiceTitle.setText("Dice");

        lblOutcomeSubtitle.setText("Outcome");

        lblTotalTitle.setText("Total");

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblDiceTotalSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDiceTotalSubtitle.setText("Dice Result:");

        lblDiceResults.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDiceResults.setText("N/A");

        lblTotalResults.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalResults.setText("N/A");

        lblTotalSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalSubtitle.setText("Total:");

        txtPreviousBets.setColumns(20);
        txtPreviousBets.setRows(5);
        jScrollPane1.setViewportView(txtPreviousBets);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSubtext1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSubtext2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(260, 260, 260)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTotalSubtitle)
                                    .addGap(29, 29, 29)
                                    .addComponent(lblTotalResults, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDiceTotalSubtitle)
                                    .addGap(29, 29, 29)
                                    .addComponent(lblDiceResults, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(16, 16, 16))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNumberGuessed, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNumGuessedSubtitle))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblBetSubtitle)
                                        .addComponent(txtBetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(72, 72, 72)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblRemainingMoney)
                                            .addGap(43, 43, 43)
                                            .addComponent(btnConfirm))
                                        .addComponent(lblMoneySubtitle)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(lblPreviousTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDiceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(lblTotalTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(lblOutcomeSubtitle))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtext1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtext2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumGuessedSubtitle)
                    .addComponent(lblBetSubtitle)
                    .addComponent(lblMoneySubtitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemainingMoney)
                    .addComponent(txtNumberGuessed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiceTotalSubtitle)
                    .addComponent(lblDiceResults))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalSubtitle)
                    .addComponent(lblTotalResults))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPreviousTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiceTitle)
                    .addComponent(lblOutcomeSubtitle)
                    .addComponent(lblTotalTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumberGuessedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberGuessedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberGuessedActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        // The user has entered a bet.
        // Define a variable to store if there is an error in the code, which will display a error statement and not run anymore code (using if statements)
        int intErrorFlag = 1;

        // First minor error handling, check if the number guessed field is empty, if so, replace it with 0
        if (txtNumberGuessed.getText().equals("") || txtNumberGuessed.equals(" ")) txtNumberGuessed.setText("0");
        // Check if the Bet amount is empty, if so, replace it with 0
        if (txtBetAmount.equals("") || txtBetAmount.equals(" ")) txtBetAmount.setText("0");
        
        // Disallow negative bet amounts
        if(Integer.parseInt(txtBetAmount.getText()) < 0) 
        {
            // Tell the program that there is a error
            intErrorFlag = 0;
            // Display to the user the fact that there is a error
            lblErrorMessage.setText("Error, bet amount cannot be negative.");
        }
        
        // Only continue if there has been no error
        if (intErrorFlag != 0)
        {
            // Unset the error message, as there is no error (hopefully).
            lblErrorMessage.setText("");
            // Push all of the previous values backwards 1, to make room for the new roll, this also overrides the last result
            for (int i = 3; i >= 0; i--)
            {
                // Push int1stDie results back 1 in the array
                int1stDie[i+1] = int1stDie[i];
                // Push int2ndDie results back 1 in the array
                int2ndDie[i+1] = int2ndDie[i];
                // Push int3rdDie results back 1 in the array
                int3rdDie[i+1] = int3rdDie[i];
                // Push strOutcome results back 1 in the array
                strOutcome[i+1] = strOutcome[i];
            }
            // Roll the first die
            int1stDie[0] = (int)(Math.random() * INTNUMFACES + 1);
            // Roll the second die
            int2ndDie[0] = (int)(Math.random() * INTNUMFACES + 1);
            // Roll the third die
            int3rdDie[0] = (int)(Math.random() * INTNUMFACES + 1);
            // Set the outcome
            if (Integer.parseInt(txtNumberGuessed.getText()) == int1stDie[0] + int2ndDie[0] + int3rdDie[0]) 
            {
                // Give the user the amount of money bet multipled by the win multiplier (you don't lose the betting money)
                intMoney += Integer.parseInt(txtBetAmount.getText()) * INTWINMULTIPLIER;
                // Set the outcome of this round to win
                strOutcome[0] = "Win";
            }
            // If they didn't win set the value to loss
            else 
            {
                // Subtract the amount of money that was bet.
                intMoney -= Integer.parseInt(txtBetAmount.getText());
                // Set the outcome of this bet to loss
                strOutcome[0] = "Loss";
            }
            
            // Display the results of the dice roll to the user
            lblDiceResults.setText(int1stDie[0] + ", " + int2ndDie[0] + ", " + int3rdDie[0]);
            // Display the total of the dice roll to the uesr
            lblTotalResults.setText((int1stDie[0] + int2ndDie[0] + int3rdDie[0]) + "");
            // Update the display on the amount of money the user has
            lblRemainingMoney.setText("$" + intMoney);
            // Declare a variable to hold some text temporarly
            String strTemp = "";
            // Now display the previous outcomes to the user
            for (int i = 0; i < 5; i++) 
            {
                // Check that that the ith previous outcome exists. (default is 0 so if it's 0 don't print anything)
                if(int1stDie[i] != 0) 
                {
                    // Add all of the information from previous bets to the temp string.
                    strTemp += ""+int1stDie[i]+", "+int2ndDie[i]+", "+int3rdDie[i]+"\t"+(int1stDie[i]+int2ndDie[i]+int3rdDie[i])+"\t"+strOutcome[i];
                    // If it's not the last element, add a newline
                    if (i != 4) strTemp += "\n";
                }
            }
            // Display the previous bets to the user
            txtPreviousBets.setText(strTemp);
        }
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        // This button will reset the whole program.
        
        // Reset the results to N/A
        lblDiceResults.setText("N/A");
        // Reset the results to N/A
        lblTotalResults.setText("N/A");
        // Update the variable amount of money
        intMoney = 100;
        // Update the display on the amount of money the starting amount
        lblRemainingMoney.setText("$"+intMoney);
        // Update the previous bets text box
        txtPreviousBets.setText("");
        // Reset all of the arrays to all 0s
        for (int i = 0; i < 5; i++)
        {
            // Reset the first die
            int1stDie[i] = 0;
            // Reset the second die
            int2ndDie[i] = 0;
            // Reset the third die
            int3rdDie[i] = 0;
            // Reset the outcome
            strOutcome[i] = "";
        }
        // reset the number guessed text box
        txtNumberGuessed.setText("0");
        // Reset the bet amount text box
        txtBetAmount.setText("0");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmU3A3AST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmU3A3AST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmU3A3AST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmU3A3AST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmU3A3AST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBetSubtitle;
    private javax.swing.JLabel lblDiceResults;
    private javax.swing.JLabel lblDiceTitle;
    private javax.swing.JLabel lblDiceTotalSubtitle;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblMoneySubtitle;
    private javax.swing.JLabel lblNumGuessedSubtitle;
    private javax.swing.JLabel lblOutcomeSubtitle;
    private javax.swing.JLabel lblPreviousTitle;
    private javax.swing.JLabel lblRemainingMoney;
    private javax.swing.JLabel lblSubtext1;
    private javax.swing.JLabel lblSubtext2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalResults;
    private javax.swing.JLabel lblTotalSubtitle;
    private javax.swing.JLabel lblTotalTitle;
    private javax.swing.JTextField txtBetAmount;
    private javax.swing.JTextField txtNumberGuessed;
    private javax.swing.JTextArea txtPreviousBets;
    // End of variables declaration//GEN-END:variables
}
